config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, :controllers => { :registrations => "welcome_mail" }, :path => 'accounts'

  root 'welcome#index'
  post 'ask' => 'welcome#ask'
  get 'about' => 'welcome#about'

  resources :recipes

end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  belongs_to :user

  field :name, type: String
  field :description, type: String
  field :notes, type: String
  field :cook_time, type: String
  field :prep_time, type: String
  field :servings, type: Integer
  field :current_step, type: Integer
  field :ingredients, type: Array
  field :steps, type: Array

  before_validation :remove_empty_steps
  before_validation :strip_steps_and_ingredients
  before_validation :remove_empty_ingredients
  before_validation :titleize_and_strip_name
  before_validation :replace_empty_strings_with_nil

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user }
  validates :steps, presence: true
  validates :ingredients, presence: true
  validates :servings, numericality: { greater_than: 0 }, allow_nil: true
  validates_with IngredientValidator

  def format_ingredient(ingredient_hash)
    if ingredient_hash["measurement"] && ingredient_hash["unit"]
      "#{ingredient_hash["measurement"]} #{ingredient_hash["unit"]} of #{ingredient_hash["name"]}"
    elsif ingredient_hash["measurement"]
      "#{ingredient_hash["measurement"]} #{ingredient_hash["name"]}"
    else
      "#{ingredient_hash["name"]}"
    end
  end

  def number_of_steps
    self["steps"].length
  end

  ["name", "steps", "current_step", "ingredients", "cook_time", "prep_time", "servings", "description", "notes"].each do |attribute|
    define_method(attribute.to_sym) do
      self[attribute]
    end
  end

  def advance_step
    if self["current_step"] < self.steps.length
      self["current_step"] += 1
      self.save
    end
  end

  def revert_step
    if self["current_step"] > 1
      self["current_step"] -= 1
      self.save
    end
  end

  def reset_step
    self["current_step"] = 1
    self.save
  end

  def go_to_step(number)
    if number.to_i > 0 && number.to_i <= self.steps.length
      self["current_step"] = number.to_i
      self.save
    end
  end

  protected
  def remove_empty_steps
    if !self.steps.nil?
      self.steps.each do |step|
        self.steps.delete(step) if !step.present?
      end
    end
  end

  def remove_empty_ingredients
    if !self.ingredients.nil?
      self.ingredients.each do |ingredient|
        if !ingredient["name"].present? && !ingredient["measurement"].present? && !ingredient["unit"].present?
          self.ingredients.delete(ingredient)
        end
        ingredient["measurement"] = nil if ingredient["measurement"] == ""
        ingredient["unit"] = nil if ingredient["unit"] == ""
      end
    end
  end

  def titleize_and_strip_name
    self.name = self.name.titleize if self.name.present?
    self.name.strip! if self.name.present?
  end

  def strip_steps_and_ingredients
    if !self.steps.nil?
      self.steps.each do |step|
        step.strip!
      end
    end

    if !self.ingredients.nil?
      self.ingredients.each do |ingredient|
        ingredient["name"].strip! if ingredient["name"]
        ingredient["measurement"].strip! if ingredient["measurement"]
        ingredient["unit"].strip! if ingredient["unit"]
      end
    end
  end

  def replace_empty_strings_with_nil
    ["name", "description", "prep_time", "cook_time", "notes"].each do |field|
      self[field].strip! if self[field].present?
      self[field] = nil unless self[field].present?
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes.order_by(name: :asc)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.attributes = recipe_params

    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cook_time, :prep_time, :servings, :notes, :ingredients => [:name, :measurement, :unit], :steps => [])
  end


end

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @recipe.errors %>
      <ul>
        <% @recipe.errors.each do |column, message| %>
          <li>
            <strong><%= column.capitalize %></strong> <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

<%= form_for @recipe, :html => { :class => "form" } do |f| %>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= f.label :name %> </h3>
    </div>
    <div class="panel-body">
      <p>The best recipe names are short and simple, like <em>Chocolate Chip Cookies</em> or <em>Pizza Dough</em>.</p>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= f.label :description %> <small><em>Optional</em></small></h3>
    </div>
    <div class="panel-body">
      <p>A short description of your delicious recipe</p>
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><%= f.label :prep_time %> <small><em>Optional</em></small></h3>
        </div>
        <div class="panel-body">
          <p> A time like
            <em>10 minutes </em>
            or
            <em>1 1/2 hours</em>
          </p>
          <%= f.text_field :prep_time, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><%= f.label :cook_time %> <small><em>Optional</em></small></h3>
        </div>
        <div class="panel-body">
          <p> A time like
            <em>10 minutes </em>
            or
            <em>1 1/2 hours</em>
          </p>
          <%= f.text_field :cook_time, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><%= f.label :servings %> <small><em>Optional</em></small></h3>
        </div>
        <div class="panel-body">
          <p> A number like
            <em>5</em>
            or
            <em>10</em>
          </p>
          <%= f.number_field :servings, min: 1, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= f.label :ingredients %></h3>
    </div>
    <div class="panel-body">
      <p>Enter each ingredient separately. See examples below.</p>
      <table class="table" id="ingredients-table">
        <thead>
          <tr>
            <th scope="col">
              Ingredient name
            </th>
            <th scope="col">
              Measurement or number <span style="font-weight: normal"><small><em>Optional</em></small></span>
            </th>
            <th scope="col">
              Unit <span style="font-weight: normal"><small><em>Optional</em></small></span>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <em>Example: flour</em>
            </td>
            <td>
              <em>1 1/2</em>
            </td>
            <td>
              <em>cups</em>
            </td>
          </tr>
          <tr>
            <td>
              <em>Example: eggs</em>
            </td>
            <td>
              <em>2</em>
            </td>
            <td></td>
          </tr>
          <tr>
            <td>
              <em>Example: salt</em>
            </td>
            <td></td>
            <td></td>
          </tr>
          <% if !@recipe.ingredients %>
            <% 5.times do %>
              <tr>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][name]">
                </td>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][measurement]">
                </td>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][unit]">
                </td>
              </tr>
            <% end %>
          <% else %>
            <% @recipe.ingredients.each do |ingredient| %>
              <tr>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][name]" value="<%=ingredient["name"]%>">
                </td>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][measurement]" value="<%=ingredient["measurement"]%>">
                </td>
                <td>
                  <input class="form-control" type="text" name="recipe[ingredients][][unit]" value="<%=ingredient["unit"]%>">
                </td>
              </tr>
            <% end %>
            <% if @recipe.ingredients.length < 5 %>
              <% (5 - @recipe.ingredients.length).times do %>
                <tr>
                  <td>
                    <input class="form-control" type="text" name="recipe[ingredients][][name]">
                  </td>
                  <td>
                    <input class="form-control" type="text" name="recipe[ingredients][][measurement]">
                  </td>
                  <td>
                    <input class="form-control" type="text" name="recipe[ingredients][][unit]">
                  </td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <button type="button" class="btn btn-info" id="more-ingredients"><i class="fa fa-plus"></i> Add more ingredients</button>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= f.label :steps %></h3>
    </div>
    <div class="panel-body">
      <p>Enter each step separately, in the way you want Alexa to read them. Short, manageable steps will work best!</p>
        <% if !@recipe.steps? %>
          <% 5.times do |n| %>
            <div class="input-group step">
              <div class="input-group-addon"><%= n + 1 %>.</div>
              <input class="form-control" type="text" name="recipe[steps][]">
            </div>
          <% end %>
        <% else %>
          <% @recipe.steps.each_with_index do |step, n| %>
            <div class="input-group step">
              <div class="input-group-addon"><%= n + 1 %>.</div>
              <input class="form-control" type="text" name="recipe[steps][]" value="<%=step%>" >
            </div>
          <% end %>
          <% if @recipe.steps.length < 5 %>
            <% (5 - @recipe.steps.length).times do |n| %>
              <div class="input-group step">
                <div class="input-group-addon"><%= @recipe.steps.length + n + 1 %>.</div>
                <input class="form-control" type="text" name="recipe[steps][]">
              </div>
            <% end %>
          <% end %>
        <% end %>
        <button type="button" class="btn btn-info" id="more-steps"><i class="fa fa-plus"></i> Add more steps</button>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"><%= f.label :notes %> <small><em>Optional</em></small></h3>
    </div>
    <div class="panel-body">
      <%= f.text_area :notes, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.submit "#{button_text}", class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<p>
  <%= link_to recipes_path do %>
    <i class="fa fa-long-arrow-left"></i> Back to My Recipes (without saving)
  <% end %>
</p>

<h1>Edit Recipe</h1>

<%= render partial: 'form', locals: { :button_text => "Save Recipe", :method => :patch } %>

app/views/recipes/index.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h1 class="panel-title recipe-card">My Recipes</h1>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to "Add a new recipe", new_recipe_path, class: "btn btn-success" %>
    </p>

  <% if current_user.recipes.empty? %>
    <p>
      You don't have any recipes! Why don't you <%= link_to "add one?", new_recipe_path %>
    </p>
  <% else %>
    <% @recipes.each do |recipe| %>
      <h2><%= link_to recipe.name, recipe_path(recipe), class: "recipe-in-list" %></h2>
    <% end %>
  <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<p>
  <%= link_to recipes_path do %>
    <i class="fa fa-long-arrow-left"></i> Back to My Recipes (without saving)
  <% end %>
</p>

<h1>New Recipe</h1>

<%= render partial: 'form', locals: { :button_text => "Save Recipe", :method => :post } %>

app/views/recipes/show.html.erb
<p>
  <%= link_to recipes_path do %>
    <i class="fa fa-long-arrow-left"></i> Back to My Recipes
  <% end %>
</p>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h1 class="panel-title recipe-card"><%= @recipe.name %></h1>
  </div>
  <div class="panel-body">
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-default" %>

    <% if @recipe.description %>
      <h3>Description</h3>
      <p><%= @recipe.description %></p>
    <% end %>

    <div class="row">
      <% attributes = {"Prep time" => @recipe.prep_time, "Cook time" => @recipe.cook_time, "Servings" => @recipe.servings} %>
      <% attributes.each do |name, value| %>
        <% if attributes[name].present? %>
          <div class="col-sm-4">
            <h3><%= name %></h3>
            <p><%= value %></p>
          </div>
        <% end %>
      <% end %>
    </div>

    <h3>Ingredients</h3>
    <% @recipe.ingredients.each do |ingredient| %>
      <% if ingredient["unit"] %>
        <p>
          <%= "#{ingredient["measurement"]} #{ingredient["unit"]} #{ingredient["name"]}" %>
        </p>
      <% elsif ingredient["measurement"] %>
        <p>
          <%= "#{ingredient["measurement"]} #{ingredient["name"]}" %>
        </p>
      <% else %>
        <p>
          <%= ingredient["name"] %>
        </p>
      <% end %>
    <% end %>

    <h3>Steps</h3>
    <% @recipe.steps.each_with_index do |step, i| %>
      <p>
        <%= i + 1 %>. <%= step %>
      </p>
    <% end %>

    <% if @recipe.notes %>
      <h3>Notes</h3>
      <p><%= @recipe.notes %></p>
    <% end %>

    <button type="button" class="btn btn-warning delete-recipe" id="delete-button"><i class="fa fa-trash-o"></i> Delete recipe?</button>

    <span style="display: none;" id="am-sure-or-cancel-zone">
      <%= link_to recipe_path(@recipe), method: :delete, class: "btn btn-danger delete-recipe" do %>
        <i class="fa fa-trash-o"></i> I'm sure
      <% end %>
      <button type="button" class="btn btn-default delete-recipe" id="cancel-delete">Cancel</button>
    </span>

  </div>
</div>