config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, :controllers => { :registrations => "welcome_mail" }, :path => 'accounts'

  root 'welcome#index'
  post 'ask' => 'welcome#ask'
  get 'about' => 'welcome#about'

  resources :recipes

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def about
  end

  def ask
    req = Request.new(params)
    response = req.route
    render :json => response.as_json, status: :ok
  end
end

app/views/welcome/about.html.erb
<div class="panel panel-primary" %>
  <div class="panel-heading">
    <h1 class="panel-title about-card">About Alexa Recipes</h1>
  </div>
  <div class="panel-body">
    <p class="about-info">
      When you're busy in the kitchen, it can be inconvenient to stop what you're doing to reference a recipe on your phone or tablet.
    </p>
    <p class="about-info">
      Alexa Recipes works alongside your <%= link_to "Amazon Echo", "http://www.amazon.com/echo" %> or other Alexa-enabled device
      to let you interact with your favorite recipes in a better way&mdash;<strong>via voice!</strong>
    </p>
  </div>
</div>

<div class="panel panel-primary" %>
  <div class="panel-heading">
    <h1 class="panel-title about-card">On this website</h1>
  </div>
  <div class="panel-body">
    <p class="about-info">
      <%= link_to "Create an account", new_user_registration_path %> on Alexa Recipes and start adding your favorite recipes.
      Then enable the Alexa Recipes skill (coming soon in the Alexa companion app) and link your Amazon Echo device to your Alexa Recipes account.
    </p>
  </div>
</div>

<div class="panel panel-primary" %>
  <div class="panel-heading">
    <h1 class="panel-title about-card">On your Alexa-enabled device</h1>
  </div>
  <div class="panel-body">
    <p class="about-info">
      On your Echo, you'll have instant voice access to all of the recipes in your Alexa Recipes account.
      Here's just a sample of what you can do with the Alexa Recipes voice skill:
    </p>
    <h2 class="about-intents">Hear a list of your recipes or open a specific recipe</h2>
    <p class="about-info">
      Alexa, ask Recipes for a list of my available recipes.
    </p>
    <p class="about-info">
      Alexa, ask Recipes to open my recipe for Chocolate Chip Cookies.
    </p>
    <h2 class="about-intents">Ask about ingredients</h2>
    <p class="about-info">
      Alexa, ask Recipes for the ingredients.
    </p>
    <p class="about-info">
      Alexa, ask Recipes how much salt I need.
    </p>
    <h2 class="about-intents">Move through a recipe step by step</h2>
    <p class="about-info">
      Alexa, tell Recipes to start over.
    </p>
    <p class="about-info">
      Alexa, tell Recipes to go to the next step.
    </p>
    <p class="about-info">
      Alexa, ask Recipes what step I'm on.
    </p>
    <p class="about-info">
      Alexa, ask Recipes how many steps are left.
    </p>
    <h2 class="about-intents">Ask about recipe details</h2>
    <p class="about-info">
      Alexa, ask Recipes how long this recipe takes.
    </p>
    <p class="about-info">
      Alexa, ask Recipes how many servings this makes.
    </p>
  </div>
</div>

<div class="panel panel-primary" %>
  <div class="panel-heading">
    <h1 class="panel-title about-card">Contact</h1>
  </div>
  <div class="panel-body">
    <p class="about-info">
      Alexa Recipes was created by Jenna Nichols as a capstone project for <%= link_to "Ada Developers Academy", "http://adadevelopersacademy.org/" %>.
      You can contact her via <%= mail_to "jennaplusplus@gmail.com", "email" %> and find her on <%= link_to "Twitter", "https://twitter.com/jennaplusplus" %>.
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6 col-sm-12 welcome-speech">
      <% if user_signed_in? %>
        <h1>Welcome back!</h1>
      <% else %>
        <h1>Create, speak, bon appétit!</h1>
      <% end %>
      <p>Alexa Recipes works alongside your Amazon Echo or other Alexa-enabled device to let you interact with your favorite recipes via voice.</p>
      <% if user_signed_in? %>
        <span class="jumbotron-buttons">
          <%= link_to 'View your recipes', recipes_path, class: 'btn btn-primary btn-lg' %>
        </span>
        <span class="jumbotron-buttons">
          <%= link_to 'Get help', about_path, class: 'btn btn-success btn-lg' %>
        </span>
      <% else %>
        <span class="jumbotron-buttons">
          <%= link_to 'Get started', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </span>
        <span class="jumbotron-buttons">
          <%= link_to 'Learn more', about_path, class: 'btn btn-success btn-lg' %>
        </span>
      <% end %>
      <p class="coming-soon-info">Available soon as a skill in the Alexa companion app.</p>
    </div>
    <div class="col-md-6 col-sm-12 welcome-logo">
      <%= image_tag("alexa-recipes-large-3.png", alt: "Alexa Recipes Logo", class: "logo") %>
    </div>
  </div>
</div>